# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
fit_Gamma <- function(Y_matrix_list, X_list, Z_list, rho, n_iter, tolerance, Gamma_list_old) {
    .Call(`_IBMR_fit_Gamma`, Y_matrix_list, X_list, Z_list, rho, n_iter, tolerance, Gamma_list_old)
}

#' @export
fit_alpha_Beta <- function(Y_matrix_list, X_list, Z_list, lambda, n_iter, tolerance, alpha_old, Beta_old) {
    .Call(`_IBMR_fit_alpha_Beta`, Y_matrix_list, X_list, Z_list, lambda, n_iter, tolerance, alpha_old, Beta_old)
}

#' @export
fit_alpha <- function(Y_matrix_list, X_list, Z_list, lambda, n_iter, tolerance, alpha_old) {
    .Call(`_IBMR_fit_alpha`, Y_matrix_list, X_list, Z_list, lambda, n_iter, tolerance, alpha_old)
}

#' @export
fit_alpha_Beta_Gamma <- function(Y_matrix_list, X_list, Z_list, lambda, rho, n_iter, tolerance, alpha_old, Beta_old, Gamma_list_old) {
    .Call(`_IBMR_fit_alpha_Beta_Gamma`, Y_matrix_list, X_list, Z_list, lambda, rho, n_iter, tolerance, alpha_old, Beta_old, Gamma_list_old)
}

compute_gradient_Beta <- function(Y_matrix_list, X_list, Z_list, alpha, Beta, Gamma_list, N) {
    .Call(`_IBMR_compute_gradient_Beta`, Y_matrix_list, X_list, Z_list, alpha, Beta, Gamma_list, N)
}

compute_gradient_alpha <- function(Y_matrix_list, X_list, Z_list, alpha, Beta, Gamma_list, N) {
    .Call(`_IBMR_compute_gradient_alpha`, Y_matrix_list, X_list, Z_list, alpha, Beta, Gamma_list, N)
}

compute_negative_log_likelihood <- function(Y_matrix_list, X_list, Z_list, alpha, Beta, Gamma_list, N) {
    .Call(`_IBMR_compute_negative_log_likelihood`, Y_matrix_list, X_list, Z_list, alpha, Beta, Gamma_list, N)
}

group_lasso_penalty <- function(Beta, lambda) {
    .Call(`_IBMR_group_lasso_penalty`, Beta, lambda)
}

l2_penalty <- function(Gamma_list, rho) {
    .Call(`_IBMR_l2_penalty`, Gamma_list, rho)
}

compute_objective_function <- function(Y_matrix_list, X_list, Z_list, alpha, Beta, Gamma_list, lambda, rho, N) {
    .Call(`_IBMR_compute_objective_function`, Y_matrix_list, X_list, Z_list, alpha, Beta, Gamma_list, lambda, rho, N)
}

#' @export
compute_probabilities <- function(X, Z, alpha, Beta, Gamma) {
    .Call(`_IBMR_compute_probabilities`, X, Z, alpha, Beta, Gamma)
}

#' @export
compute_probabilities_Gamma0 <- function(X, alpha, Beta) {
    .Call(`_IBMR_compute_probabilities_Gamma0`, X, alpha, Beta)
}

#' @export
compute_conditional_probabilities <- function(Y_matrix, P) {
    .Call(`_IBMR_compute_conditional_probabilities`, Y_matrix, P)
}

group_lasso_prox <- function(matrix, lambda) {
    .Call(`_IBMR_group_lasso_prox`, matrix, lambda)
}

rcpparma_hello_world <- function() {
    .Call(`_IBMR_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_IBMR_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_IBMR_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_IBMR_rcpparma_bothproducts`, x)
}

update_Beta <- function(Y_matrix_list, X_list, Z_list, alpha, Beta_old, Gamma_list, lambda, N) {
    .Call(`_IBMR_update_Beta`, Y_matrix_list, X_list, Z_list, alpha, Beta_old, Gamma_list, lambda, N)
}

update_alpha <- function(Y_matrix_list, X_list, Z_list, alpha_old, Beta, Gamma_list, N) {
    .Call(`_IBMR_update_alpha`, Y_matrix_list, X_list, Z_list, alpha_old, Beta, Gamma_list, N)
}

update_Gamma_list <- function(Y_matrix_list, X_list, Z_list, alpha, Beta, Gamma_list_old, rho, N) {
    .Call(`_IBMR_update_Gamma_list`, Y_matrix_list, X_list, Z_list, alpha, Beta, Gamma_list_old, rho, N)
}

